# autoMate机器人token
autoMate_token: 
  MTI2MDgwODg5OTA1Nzk0MjU4OQ.GiX8-B.px0HX8yRxBeYw2IYnB0_3aJc3pSGvIezTHnV7E

# mysql连接参数
mysql:
  username: discordbot
  password: 96b0_8GoLl^y7!Vm(T.2fWY?dJe41HQv
  host: 116.198.240.197
  port: 3306
  database: discordbot_test